### ISSUE TITLE
generate_databases function - generate higher dimensional databases

### ISSUE THREAD

**Issue by JonMuehlst** [cmla-psu/statdp#1]
Could you please add some higher dimensional databases under generators.py?

**Comment by yuxincs** [comment]
Hi @JonMuehlst, thanks for the interests in our project.

Could you clarify "higher dimensional databases"? Are you referring to input database like D1: [[1, 2], [3, 4]] D2: [[5, 6], [7, 8]]?

Unfortunately our tool was designed over numerical queries, `test_statistics` might be re-used (as this is the core of hypothesis testing), other part of the project (`event selector` / `database generator`) might have to be changed a little to suit your need.

I can provide more help if you can make your needs clearer.

**Comment by JonMuehlst** [comment]
Hi @RyanWangGit, thank you for this important project.

Yes D1: [[1, 2], [3, 4]] D2: [[5, 6], [7, 8]] is a good example. I'm also interested in higher dimensional databases D1: [[1, 2, 3], [4, 5, 6]] D2: [[7, 8, 9], [10, 11, 12]] etc...

Any guidance / help will be much appreciated.

**Comment by yuxincs** [comment]
Hi @JonMuehlst, sorry for the late reply.

I understand, actually I think this is not hard to do. Instead of using our simple input generator, you can specify an *adjacent* D1 and D2 (depending on your definition of *adjacent*, on numerical queries we define *adjacent* as `|q(D2) - q(D1)| <= delta` where delta is the sensitivity and we assume the sensitivity is 1) through parameter `databases` of function `detect_counterexamples`.

Our tool doesn't care how your source code looks like as long as you provide all necessary extra arguments, and you can feed in whatever data you like to your algorithm. It mainly deals with the output and does hypothesis test on that.

To make it more clear, assume your algorithm is defined as 
```
def your_algorithm(Q, epsilon, ...):
  # here your algorithm should be able to process high-dimensional input Q
  ...
  # for best performance, you may want to convert your output to a number for test
  # possible choices are *hamming distance* / *length of list* / *number of falses* etc.
  # refer to our paper Section 4.3 and statdp/algorithms.py
  return x

if __name__== '__main__':
  kwargs = {'epsilon': your_algorithm_epsilon, extra_arguments}
  D1, D2 = numpy.array([[1, 1], [2, 2]]), numpy.array([[2, 2], [1, 1]])
  detect_counterexample(your_algorithm, epsilon_to_test, kwargs, databases=(D1, D2))
```

If you have any questions or any part I didn't make clear, please don't hesitate to reply.

**Comment by JonMuehlst** [comment]
Hi @RyanWangGit, thanks for the detailed reply!

So I understand that as long as the input data D1, D2 are adjacent the framework will work.
Could you please specify what is meant by 'q' in `|q(D2) - q(D1)| <= delta` ? 

Thank you for the sample code. Is there anything which should be considered when defining the adjacent input data? In terms of run-time or otherwise?

**Comment by yuxincs** [comment]
Hi @JonMuehlst ,

Actually the framework doesn't need or enforce the input data D1, D2 to be *adjacent*, but it doesn't make sense if the D1, D2 is not. This is a framework to find violations of differential privacy, informally by definition differential privacy only enforces properties on *adjacent* input. It is a requirement from differential privacy instead of our framework. For more details I have to refer you to the Section 3.1 of our paper.

The `q` in `|q(D2) - q(D1)| <= delta` means any query in database `D1` or `D2`. For example, if D1 is `[1, 2, 3, 4]` D2 is `[0, 3, 2, 5]`, `q(D1)` means any element in `[1, 2, 3, 4]`. So the statement `|q(D2) - q(D1)| <= delta` enforces that any element in `D2` can only differ from the corresponding element from `D1` (with the same index) by at most `delta`.

I'd like to help you further if there's any part I didn't make myself clear.
